In [5]:
import pandas as pd
import plotly.express as px
import numpy as np
from datetime import datetime

In [6]:
df = pd.read_csv('data/data.csv', header=None, delimiter=';')
df.columns = ['timestamp', 'station_id', 'mechanical_bike', 'electrical_bike', 'available_dock', 'is_renting', 'is_receiving']

In [7]:
df['total_bike'] = df.mechanical_bike + df.electrical_bike
df['capacity'] = df.total_bike + df.available_dock
df['timestamp'] = pd.to_datetime(df['timestamp'] * 60, unit='s') # Converting minutes to seconds
df['timestamp'] = df['timestamp'].dt.strftime('%d/%m/%y - %H:%M')

# df = df.groupby('station_id', as_index=False).agg('mean')
# df = df.sort_values(['electrical_bike', 'mechanical_bike'], ascending=False)
df.head(50)

,timestamp,station_id,mechanical_bike,electrical_bike,available_dock,is_renting,is_receiving,total_bike,capacity
0,16/04/23 - 19:20,213688169,0.0,1.0,34,1,1,1.0,35.0
1,16/04/23 - 19:20,653222953,7.0,5.0,18,1,1,12.0,30.0
2,16/04/23 - 19:20,36255,5.0,2.0,14,1,1,7.0,21.0
3,16/04/23 - 19:20,37815204,10.0,3.0,17,1,1,13.0,30.0
4,16/04/23 - 19:20,17278902806,0.0,0.0,0,0,0,0.0,0.0
5,16/04/23 - 19:20,251039991,0.0,3.0,22,1,1,3.0,25.0
6,16/04/23 - 19:20,85002689,3.0,2.0,52,1,1,5.0,57.0
7,16/04/23 - 19:20,2515829865,2.0,10.0,8,1,1,12.0,20.0
8,16/04/23 - 19:20,516709288,0.0,1.0,18,1,1,1.0,19.0
9,16/04/23 - 19:20,120827885,1.0,2.0,9,1,1,3.0,12.0
10,16/04/23 - 19:20,37874517,2.0,1.0,18,1,1,3.0,21.0
11,16/04/23 - 19:20,66491398,5.0,9.0,33,1,1,14.0,47.0
12,16/04/23 - 19:20,17486274358,0.0,0.0,0,0,0,0.0,0.0
13,16/04/23 - 19:20,210403080,1.0,3.0,17,1,1,4.0,21.0
14,16/04/23 - 19:20,210561800,8.0,4.0,3,1,1,12.0,15.0
15,16/04/23 - 19:20,209063434,9.0,3.0,17,1,1,12.0,29.0
16,16/04/23 - 19:20,94555589,3.0,6.0,17,1,1,9.0,26.0
17,16/04/23 - 19:20,244498842,29.0,14.0,6,1,1,43.0,49.0
18,16/04/23 - 19:20,210405211,5.0,0.0,15,1,1,5.0,20.0
19,16/04/23 - 19:20,43195240,2.0,8.0,15,1,1,10.0,25.0
20,16/04/23 - 19:20,501862076,0.0,5.0,15,1,1,5.0,20.0
21,16/04/23 - 19:20,100769544,33.0,1.0,6,1,1,34.0,40.0
22,16/04/23 - 19:20,207633746,5.0,4.0,51,1,1,9.0,60.0
23,16/04/23 - 19:20,16560752067,3.0,0.0,27,1,1,3.0,30.0
24,16/04/23 - 19:20,210566542,2.0,1.0,56,1,1,3.0,59.0
25,16/04/23 - 19:20,210565680,23.0,2.0,8,1,1,25.0,33.0
26,16/04/23 - 19:20,85043758,10.0,3.0,22,1,1,13.0,35.0
27,16/04/23 - 19:20,54000559,3.0,5.0,13,1,1,8.0,21.0
28,16/04/23 - 19:20,210397939,4.0,1.0,12,1,1,5.0,17.0
29,16/04/23 - 19:20,82405965,36.0,3.0,3,1,1,39.0,42.0
30,16/04/23 - 19:20,213682736,0.0,5.0,47,1,1,5.0,52.0
31,16/04/23 - 19:20,128986726,1.0,0.0,32,1,1,1.0,33.0
32,16/04/23 - 19:20,54000581,5.0,6.0,22,1,1,11.0,33.0
33,16/04/23 - 19:20,13105968,1.0,0.0,20,1,1,1.0,21.0
34,16/04/23 - 19:20,653208733,0.0,1.0,37,1,1,1.0,38.0
35,16/04/23 - 19:20,27415224,21.0,9.0,2,1,1,30.0,32.0
36,16/04/23 - 19:20,907054879,17.0,0.0,3,1,1,17.0,20.0
37,16/04/23 - 19:20,123095125,8.0,1.0,49,1,1,9.0,58.0
38,16/04/23 - 19:20,129094535,1.0,1.0,37,1,1,2.0,39.0
39,16/04/23 - 19:20,54000612,5.0,3.0,33,1,1,8.0,41.0
40,16/04/23 - 19:20,80101533,2.0,5.0,26,1,1,7.0,33.0
41,16/04/23 - 19:20,599135701,6.0,7.0,28,1,1,13.0,41.0
42,16/04/23 - 19:20,102747146,1.0,4.0,18,1,1,5.0,23.0
43,16/04/23 - 19:20,2515403527,1.0,0.0,25,1,1,1.0,26.0
44,16/04/23 - 19:20,653132534,3.0,2.0,20,1,1,5.0,25.0
45,16/04/23 - 19:20,506455295,0.0,0.0,16,1,1,0.0,16.0
46,16/04/23 - 19:20,1057149522,4.0,6.0,11,1,1,10.0,21.0
47,16/04/23 - 19:20,210567545,9.0,0.0,8,1,1,9.0,17.0
48,16/04/23 - 19:20,653197324,7.0,11.0,4,1,1,18.0,22.0
49,16/04/23 - 19:20,2515085147,3.0,2.0,14,1,1,5.0,19.0

In [8]:
df_stations = pd.read_json('data/data.json')
df_stations

,station_id,name,lat,lon,capacity,stationCode,rental_methods
0,213688169,Benjamin Godard - Victor Hugo,48.865983,2.275725,35,16107,NaN
1,653222953,Mairie de Rosny-sous-Bois,48.871257,2.486581,30,31104,[CREDITCARD]
2,36255,Toudouze - Clauzel,48.879296,2.337360,21,9020,[CREDITCARD]
3,37815204,Mairie du 12ème,48.840855,2.387555,30,12109,NaN
4,17278902806,Rouget de L'isle - Watteau,48.778193,2.396302,0,44015,NaN
...,...,...,...,...,...,...,...
1459,54000604,Ordener - Poissonniers,48.891214,2.351289,35,18023,[CREDITCARD]
1460,43247738,Ruisseau - Ordener,48.892995,2.340145,35,18026,[CREDITCARD]
1461,102311820,Clignancourt - Ordener,48.891458,2.348636,35,18024,[CREDITCARD]
1462,368766689,Westermeyer - Paul Vaillant-Couturier,48.819116,2.396664,25,42004,[CREDITCARD]
1463,315022587,Malesherbes - Place de la Madeleine,48.870406,2.323244,67,8004,[CREDITCARD]

In [9]:
df = pd.merge(df, df_stations[['station_id', 'name', 'lat', 'lon']], on=['station_id'], how='left')
df = df.drop('station_id', axis=1)
df['station_fill'] = np.where(df.capacity == 0, 0, df.total_bike / df.capacity)

df.head(50)

,timestamp,mechanical_bike,electrical_bike,available_dock,is_renting,is_receiving,total_bike,capacity,name,lat,lon,station_fill
0,16/04/23 - 19:20,0.0,1.0,34,1,1,1.0,35.0,Benjamin Godard - Victor Hugo,48.865983,2.275725,0.028571
1,16/04/23 - 19:20,7.0,5.0,18,1,1,12.0,30.0,Mairie de Rosny-sous-Bois,48.871257,2.486581,0.400000
2,16/04/23 - 19:20,5.0,2.0,14,1,1,7.0,21.0,Toudouze - Clauzel,48.879296,2.337360,0.333333
3,16/04/23 - 19:20,10.0,3.0,17,1,1,13.0,30.0,Mairie du 12ème,48.840855,2.387555,0.433333
4,16/04/23 - 19:20,0.0,0.0,0,0,0,0.0,0.0,Rouget de L'isle - Watteau,48.778193,2.396302,0.000000
5,16/04/23 - 19:20,0.0,3.0,22,1,1,3.0,25.0,Cassini - Denfert-Rochereau,48.837526,2.336035,0.120000
6,16/04/23 - 19:20,3.0,2.0,52,1,1,5.0,57.0,Jourdan - Stade Charléty,48.819428,2.343335,0.087719
7,16/04/23 - 19:20,2.0,10.0,8,1,1,12.0,20.0,Basilique,48.936269,2.358867,0.600000
8,16/04/23 - 19:20,0.0,1.0,18,1,1,1.0,19.0,Charonne - Robert et Sonia Delaunay,48.855908,2.392571,0.052632
9,16/04/23 - 19:20,1.0,2.0,9,1,1,3.0,12.0,Messine - Place Du Pérou,48.875448,2.315508,0.250000
10,16/04/23 - 19:20,2.0,1.0,18,1,1,3.0,21.0,Saint-Sulpice,48.851654,2.330808,0.142857
11,16/04/23 - 19:20,5.0,9.0,33,1,1,14.0,47.0,Le Brun - Gobelins,48.835093,2.353468,0.297872
12,16/04/23 - 19:20,0.0,0.0,0,0,0,0.0,0.0,Jean Rostand - Paul Vaillant Couturier,48.908168,2.453060,0.000000
13,16/04/23 - 19:20,1.0,3.0,17,1,1,4.0,21.0,Lacépède - Monge,48.843893,2.351966,0.190476
14,16/04/23 - 19:20,8.0,4.0,3,1,1,12.0,15.0,Saint-Romain - Cherche-Midi,48.847082,2.321375,0.800000
15,16/04/23 - 19:20,9.0,3.0,17,1,1,12.0,29.0,André Karman - République,48.910399,2.385136,0.413793
16,16/04/23 - 19:20,3.0,6.0,17,1,1,9.0,26.0,Pierre et Marie Curie - Maurice Thorez,48.815802,2.376805,0.346154
17,16/04/23 - 19:20,29.0,14.0,6,1,1,43.0,49.0,Bois de Vincennes - Gare,48.836022,2.470834,0.877551
18,16/04/23 - 19:20,5.0,0.0,15,1,1,5.0,20.0,Beaux-Arts - Bonaparte,48.856452,2.334852,0.250000
19,16/04/23 - 19:20,2.0,8.0,15,1,1,10.0,25.0,Silly - Galliéni,48.835584,2.232550,0.400000
20,16/04/23 - 19:20,0.0,5.0,15,1,1,5.0,20.0,Place Nelson Mandela,48.862091,2.196576,0.250000
21,16/04/23 - 19:20,33.0,1.0,6,1,1,34.0,40.0,Harpe - Saint-Germain,48.851519,2.343670,0.850000
22,16/04/23 - 19:20,5.0,4.0,51,1,1,9.0,60.0,Grande Armée - Brunel,48.876116,2.288124,0.150000
23,16/04/23 - 19:20,3.0,0.0,27,1,1,3.0,30.0,Bracion - Périphérique,48.826104,2.300455,0.100000
24,16/04/23 - 19:20,2.0,1.0,56,1,1,3.0,59.0,Square Boucicaut,48.851296,2.325062,0.050847
25,16/04/23 - 19:20,23.0,2.0,8,1,1,25.0,33.0,Vaneau - Sèvres,48.848563,2.320422,0.757576
26,16/04/23 - 19:20,10.0,3.0,22,1,1,13.0,35.0,Guersant - Gouvion-Saint-Cyr,48.882878,2.287667,0.371429
27,16/04/23 - 19:20,3.0,5.0,13,1,1,8.0,21.0,Jouffroy d'Abbans - Wagram,48.881973,2.301132,0.380952
28,16/04/23 - 19:20,4.0,1.0,12,1,1,5.0,17.0,Thouin - Cardinal Lemoine,48.845047,2.349465,0.294118
29,16/04/23 - 19:20,36.0,3.0,3,1,1,39.0,42.0,Froment - Bréguet,48.857041,2.372895,0.928571
30,16/04/23 - 19:20,0.0,5.0,47,1,1,5.0,52.0,Morillons - Dantzig,48.833101,2.299380,0.096154
31,16/04/23 - 19:20,1.0,0.0,32,1,1,1.0,33.0,Boétie - Ponthieu,48.871417,2.307679,0.030303
32,16/04/23 - 19:20,5.0,6.0,22,1,1,11.0,33.0,Croulebarde - Corvisart,48.830982,2.348165,0.333333
33,16/04/23 - 19:20,1.0,0.0,20,1,1,1.0,21.0,Le Brix et Mesmin - Jourdan,48.822341,2.327862,0.047619
34,16/04/23 - 19:20,0.0,1.0,37,1,1,1.0,38.0,Romainville - Vaillant-Couturier,48.867850,2.446748,0.026316
35,16/04/23 - 19:20,21.0,9.0,2,1,1,30.0,32.0,Bir Hakeim,48.853844,2.289705,0.937500
36,16/04/23 - 19:20,17.0,0.0,3,1,1,17.0,20.0,Liberté - Vert-de-Maisons,48.790148,2.432863,0.850000
37,16/04/23 - 19:20,8.0,1.0,49,1,1,9.0,58.0,Alibert - Jemmapes,48.871044,2.366104,0.155172
38,16/04/23 - 19:20,1.0,1.0,37,1,1,2.0,39.0,Porte de Saint-Ouen - Bessières,48.897922,2.328515,0.051282
39,16/04/23 - 19:20,5.0,3.0,33,1,1,8.0,41.0,Cambrai - Benjamin Constant,48.895947,2.381134,0.195122
40,16/04/23 - 19:20,2.0,5.0,26,1,1,7.0,33.0,Chazelles - Courcelles,48.879407,2.303446,0.212121
41,16/04/23 - 19:20,6.0,7.0,28,1,1,13.0,41.0,Ramponeau - Belleville,48.871031,2.379057,0.317073
42,16/04/23 - 19:20,1.0,4.0,18,1,1,5.0,23.0,Lagny - Victor Basch,48.848841,2.426325,0.217391
43,16/04/23 - 19:20,1.0,0.0,25,1,1,1.0,26.0,Saint-Cloud - Hippodrome,48.857721,2.254911,0.038462
44,16/04/23 - 19:20,3.0,2.0,20,1,1,5.0,25.0,Louis Lejeune - Barbès,48.818074,2.326701,0.200000
45,16/04/23 - 19:20,0.0,0.0,16,1,1,0.0,16.0,Général Martial Valin - Pont du Garigliano,48.838231,2.270506,0.000000
46,16/04/23 - 19:20,4.0,6.0,11,1,1,10.0,21.0,Rond-point du Dr Albert Schweitzer,48.789809,2.314394,0.476190
47,16/04/23 - 19:20,9.0,0.0,8,1,1,9.0,17.0,Raspail - Varenne,48.853148,2.326391,0.529412
48,16/04/23 - 19:20,7.0,11.0,4,1,1,18.0,22.0,Théâtre des Amandiers - Palais des sports,48.892649,2.213694,0.818182
49,16/04/23 - 19:20,3.0,2.0,14,1,1,5.0,19.0,Italie - Tolbiac,48.825572,2.357617,0.263158

In [10]:
fig = px.density_mapbox(df, lat='lat', lon='lon', z='station_fill', hover_name='name', hover_data='station_fill',
                        center=dict(lat=48.8566, lon=2.3522), zoom=12, width=1500, height=800,
                        mapbox_style="carto-positron",
                        radius=40, opacity=0.5)
#fig.show()

In [11]:
df['ratio_electric'] = np.where(df.total_bike == 0, 0, df.electrical_bike / df.total_bike)

In [12]:
last_timestamp = df['timestamp'].max()
df = df[df['timestamp'] == last_timestamp]
datetime.fromtimestamp(last_timestamp * 60).strftime('%d/%m/%y - %H:%M')

TypeError: an integer is required (got type str)

In [ ]:
fig = px.scatter_mapbox(df, lat='lat', lon='lon', size='station_fill', hover_name='name', color='ratio_electric',
                        center=dict(lat=48.8566, lon=2.3522), zoom=12, width=1500, height=800,
                        mapbox_style="carto-positron", opacity=0.5)
# fig.show()