In [48]:
import pandas as pd
import plotly.express as px
import numpy as np
from datetime import datetime

In [49]:
df = pd.read_csv('data/data.csv', header=None, delimiter=';')
df.columns = ['timestamp', 'station_id', 'mechanical_bike', 'electrical_bike', 'available_dock', 'is_renting', 'is_receiving']

In [50]:
df['total_bike'] = df.mechanical_bike + df.electrical_bike
df['capacity'] = df.total_bike + df.available_dock
#df = df.groupby('station_id', as_index=False).agg('mean')
#df = df.sort_values(['electrical_bike', 'mechanical_bike'], ascending=False)
df.head(50)

,timestamp,station_id,mechanical_bike,electrical_bike,available_dock,is_renting,is_receiving,total_bike,capacity
0,28027580,213688169,0,2,33,1,1,2,35
1,28027580,653222953,7,2,21,1,1,9,30
2,28027580,36255,2,3,16,1,1,5,21
3,28027580,37815204,0,2,28,1,1,2,30
4,28027580,17278902806,0,0,0,0,0,0,0
5,28027580,251039991,1,2,22,1,1,3,25
6,28027580,85002689,9,12,36,1,1,21,57
7,28027580,2515829865,3,7,10,1,1,10,20
8,28027580,516709288,0,2,17,1,1,2,19
9,28027580,120827885,1,0,11,1,1,1,12
10,28027580,37874517,10,3,8,1,1,13,21
11,28027580,66491398,1,1,46,1,1,2,48
12,28027580,17486274358,0,0,0,0,0,0,0
13,28027580,210403080,4,7,10,1,1,11,21
14,28027580,210561800,3,0,13,1,1,3,16
15,28027580,209063434,11,4,14,1,1,15,29
16,28027580,94555589,0,0,26,1,1,0,26
17,28027580,244498842,20,13,15,1,1,33,48
18,28027580,210405211,6,0,14,1,1,6,20
19,28027580,43195240,4,7,14,1,1,11,25
20,28027580,501862076,0,3,17,1,1,3,20
21,28027580,100769544,28,9,3,1,1,37,40
22,28027580,207633746,1,3,57,1,1,4,61
23,28027580,16560752067,1,3,26,1,1,4,30
24,28027580,210566542,13,6,40,1,1,19,59
25,28027580,210565680,2,1,31,1,1,3,34
26,28027580,85043758,0,4,31,1,1,4,35
27,28027580,54000559,0,0,22,1,1,0,22
28,28027580,210397939,4,1,12,1,1,5,17
29,28027580,82405965,16,0,26,1,1,16,42
30,28027580,213682736,0,1,51,1,1,1,52
31,28027580,128986726,1,0,32,1,1,1,33
32,28027580,54000581,4,1,28,1,1,5,33
33,28027580,13105968,2,1,18,1,1,3,21
34,28027580,653208733,0,0,38,1,1,0,38
35,28027580,27415224,19,4,10,1,1,23,33
36,28027580,907054879,18,1,1,1,1,19,20
37,28027580,123095125,0,5,54,1,1,5,59
38,28027580,129094535,0,1,37,1,1,1,38
39,28027580,54000612,1,1,39,1,1,2,41
40,28027580,80101533,0,2,31,1,1,2,33
41,28027580,599135701,1,0,40,1,1,1,41
42,28027580,102747146,3,2,19,1,1,5,24
43,28027580,2515403527,5,5,18,1,1,10,28
44,28027580,653132534,0,0,25,1,1,0,25
45,28027580,506455295,6,2,8,1,1,8,16
46,28027580,1057149522,3,4,13,1,1,7,20
47,28027580,210567545,10,7,0,1,1,17,17
48,28027580,653197324,6,13,3,1,1,19,22
49,28027580,2515085147,0,1,18,1,1,1,19

In [51]:
df_stations = pd.read_json('data/data.json')
df_stations

,station_id,name,lat,lon,capacity,stationCode,rental_methods
0,213688169,Benjamin Godard - Victor Hugo,48.865983,2.275725,35,16107,NaN
1,653222953,Mairie de Rosny-sous-Bois,48.871257,2.486581,30,31104,[CREDITCARD]
2,36255,Toudouze - Clauzel,48.879296,2.337360,21,9020,[CREDITCARD]
3,37815204,Mairie du 12ème,48.840855,2.387555,30,12109,NaN
4,17278902806,Rouget de L'isle - Watteau,48.778193,2.396302,0,44015,NaN
...,...,...,...,...,...,...,...
1459,54000604,Ordener - Poissonniers,48.891214,2.351289,35,18023,[CREDITCARD]
1460,43247738,Ruisseau - Ordener,48.892995,2.340145,35,18026,[CREDITCARD]
1461,102311820,Clignancourt - Ordener,48.891458,2.348636,35,18024,[CREDITCARD]
1462,368766689,Westermeyer - Paul Vaillant-Couturier,48.819116,2.396664,25,42004,[CREDITCARD]
1463,315022587,Malesherbes - Place de la Madeleine,48.870406,2.323244,67,8004,[CREDITCARD]

In [52]:
df = pd.merge(df, df_stations[['station_id', 'name', 'lat', 'lon']], on=['station_id'], how='left')
df = df.drop('station_id', axis=1)
df['station_fill'] = np.where(df.capacity == 0, 0, df.total_bike / df.capacity)

df.head(50)

,timestamp,mechanical_bike,electrical_bike,available_dock,is_renting,is_receiving,total_bike,capacity,name,lat,lon,station_fill
0,28027580,0,2,33,1,1,2,35,Benjamin Godard - Victor Hugo,48.865983,2.275725,0.057143
1,28027580,7,2,21,1,1,9,30,Mairie de Rosny-sous-Bois,48.871257,2.486581,0.300000
2,28027580,2,3,16,1,1,5,21,Toudouze - Clauzel,48.879296,2.337360,0.238095
3,28027580,0,2,28,1,1,2,30,Mairie du 12ème,48.840855,2.387555,0.066667
4,28027580,0,0,0,0,0,0,0,Rouget de L'isle - Watteau,48.778193,2.396302,0.000000
5,28027580,1,2,22,1,1,3,25,Cassini - Denfert-Rochereau,48.837526,2.336035,0.120000
6,28027580,9,12,36,1,1,21,57,Jourdan - Stade Charléty,48.819428,2.343335,0.368421
7,28027580,3,7,10,1,1,10,20,Basilique,48.936269,2.358867,0.500000
8,28027580,0,2,17,1,1,2,19,Charonne - Robert et Sonia Delaunay,48.855908,2.392571,0.105263
9,28027580,1,0,11,1,1,1,12,Messine - Place Du Pérou,48.875448,2.315508,0.083333
10,28027580,10,3,8,1,1,13,21,Saint-Sulpice,48.851654,2.330808,0.619048
11,28027580,1,1,46,1,1,2,48,Le Brun - Gobelins,48.835093,2.353468,0.041667
12,28027580,0,0,0,0,0,0,0,Jean Rostand - Paul Vaillant Couturier,48.908168,2.453060,0.000000
13,28027580,4,7,10,1,1,11,21,Lacépède - Monge,48.843893,2.351966,0.523810
14,28027580,3,0,13,1,1,3,16,Saint-Romain - Cherche-Midi,48.847082,2.321375,0.187500
15,28027580,11,4,14,1,1,15,29,André Karman - République,48.910399,2.385136,0.517241
16,28027580,0,0,26,1,1,0,26,Pierre et Marie Curie - Maurice Thorez,48.815802,2.376805,0.000000
17,28027580,20,13,15,1,1,33,48,Bois de Vincennes - Gare,48.836022,2.470834,0.687500
18,28027580,6,0,14,1,1,6,20,Beaux-Arts - Bonaparte,48.856452,2.334852,0.300000
19,28027580,4,7,14,1,1,11,25,Silly - Galliéni,48.835584,2.232550,0.440000
20,28027580,0,3,17,1,1,3,20,Place Nelson Mandela,48.862091,2.196576,0.150000
21,28027580,28,9,3,1,1,37,40,Harpe - Saint-Germain,48.851519,2.343670,0.925000
22,28027580,1,3,57,1,1,4,61,Grande Armée - Brunel,48.876116,2.288124,0.065574
23,28027580,1,3,26,1,1,4,30,Bracion - Périphérique,48.826104,2.300455,0.133333
24,28027580,13,6,40,1,1,19,59,Square Boucicaut,48.851296,2.325062,0.322034
25,28027580,2,1,31,1,1,3,34,Vaneau - Sèvres,48.848563,2.320422,0.088235
26,28027580,0,4,31,1,1,4,35,Guersant - Gouvion-Saint-Cyr,48.882878,2.287667,0.114286
27,28027580,0,0,22,1,1,0,22,Jouffroy d'Abbans - Wagram,48.881973,2.301132,0.000000
28,28027580,4,1,12,1,1,5,17,Thouin - Cardinal Lemoine,48.845047,2.349465,0.294118
29,28027580,16,0,26,1,1,16,42,Froment - Bréguet,48.857041,2.372895,0.380952
30,28027580,0,1,51,1,1,1,52,Morillons - Dantzig,48.833101,2.299380,0.019231
31,28027580,1,0,32,1,1,1,33,Boétie - Ponthieu,48.871417,2.307679,0.030303
32,28027580,4,1,28,1,1,5,33,Croulebarde - Corvisart,48.830982,2.348165,0.151515
33,28027580,2,1,18,1,1,3,21,Le Brix et Mesmin - Jourdan,48.822341,2.327862,0.142857
34,28027580,0,0,38,1,1,0,38,Romainville - Vaillant-Couturier,48.867850,2.446748,0.000000
35,28027580,19,4,10,1,1,23,33,Bir Hakeim,48.853844,2.289705,0.696970
36,28027580,18,1,1,1,1,19,20,Liberté - Vert-de-Maisons,48.790148,2.432863,0.950000
37,28027580,0,5,54,1,1,5,59,Alibert - Jemmapes,48.871044,2.366104,0.084746
38,28027580,0,1,37,1,1,1,38,Porte de Saint-Ouen - Bessières,48.897922,2.328515,0.026316
39,28027580,1,1,39,1,1,2,41,Cambrai - Benjamin Constant,48.895947,2.381134,0.048780
40,28027580,0,2,31,1,1,2,33,Chazelles - Courcelles,48.879407,2.303446,0.060606
41,28027580,1,0,40,1,1,1,41,Ramponeau - Belleville,48.871031,2.379057,0.024390
42,28027580,3,2,19,1,1,5,24,Lagny - Victor Basch,48.848841,2.426325,0.208333
43,28027580,5,5,18,1,1,10,28,Saint-Cloud - Hippodrome,48.857721,2.254911,0.357143
44,28027580,0,0,25,1,1,0,25,Louis Lejeune - Barbès,48.818074,2.326701,0.000000
45,28027580,6,2,8,1,1,8,16,Général Martial Valin - Pont du Garigliano,48.838231,2.270506,0.500000
46,28027580,3,4,13,1,1,7,20,Rond-point du Dr Albert Schweitzer,48.789809,2.314394,0.350000
47,28027580,10,7,0,1,1,17,17,Raspail - Varenne,48.853148,2.326391,1.000000
48,28027580,6,13,3,1,1,19,22,Théâtre des Amandiers - Palais des sports,48.892649,2.213694,0.863636
49,28027580,0,1,18,1,1,1,19,Italie - Tolbiac,48.825572,2.357617,0.052632

In [53]:
fig = px.density_mapbox(df, lat='lat', lon='lon', z='station_fill', hover_name='name', hover_data='station_fill',
                        center=dict(lat=48.8566, lon=2.3522), zoom=12, width=1500, height=800,
                        mapbox_style="carto-positron",
                        radius=40, opacity=0.5)
#fig.show()

In [54]:
df['ratio_electric'] = np.where(df.total_bike == 0, 0, df.electrical_bike / df.total_bike)

In [55]:
last_timestamp = df['timestamp'].max()
df = df[df['timestamp'] == last_timestamp]
datetime.fromtimestamp(last_timestamp * 60).strftime('%d/%m/%y - %H:%M')

'16/04/23 - 16:20'

In [56]:
fig = px.scatter_mapbox(df, lat='lat', lon='lon', size='station_fill', hover_name='name', color='ratio_electric',
                        center=dict(lat=48.8566, lon=2.3522), zoom=12, width=1500, height=800,
                        mapbox_style="carto-positron", opacity=0.5)
# fig.show()